### PR TITLE
Enable and fix unit tests

### LINKED ISSUE #5: Enable and fix unit tests for ENVI
Currently, unit tests are disabled as they do not work as expected. This must be fixed in a separate PR.

**Note:** Please, check if R CMD passes locally before pushing commits to GitHub.

### PR DESCRIPTION
**Pull request by GegznaV**
Originally these changes were introduced in 325f550 by @sangttruong (just `styler` was applied to use the Tidyverse style).

@sangttruong, why was the change of hash codes needed? What changed in imported files? Is it purely due to changed paths?

***

Could @cbeleites (as she knows the ENVI format best) or @sangttruong (as he worked on this issue currently) take care to fix this?

Related: #5

### CODE REVIEW

**Comment by cbeleites** [comment]
Hi @GegznaV the main issue was actually a bug, see https://github.com/r-hyperspec/hySpc.read.ENVI/pull/6/commits/be735513c8dfd9b59ba9ecf561234941345da64c

Looks like `R CMD check` is more strict in some ways than `devtools::test()`.

**Comment by cbeleites** [comment]
@sangttruong or @GegznaV  could you re-write the tests that still check hash code to more direct checks of the object content? 

The hash codes turn out to be quite fragile in practice. I've needed to change them quite often, without actual changes in the object (updates to **digest** package etc.)

**Comment by GegznaV** [comment]
> The hash codes turn out to be quite fragile in practice.

I think this will be solved when we move to `testthat` 3 ed. The function `expect_known_hash()` is deprecated there and, if I understand correctly, the mechanism to check a "snapshot" of the object is more stable and reliable in 3 ed. as the authors of  `testthat` wanted to enhance reproducibility.
 
 If the tests work now, I suggest merging this PR and not making it bigger as the main purpose of this PR was to enable unit tests after migrating them to a new repo. After merging, we should open a new issue on this and solve it in separate PRs. Would that be OK for you, @cbeleites?

**Comment by cbeleites** [comment]
That's fine with me. Just seemed to belong to the topic of issue #5

**Pull request merged**
